### ISSUE TITLE
코드 대공사 (Description 확인!)

### ISSUE THREAD

**Issue by HongJaeMin** [DS-Job-Flow/test-repo#18]
## Description

새로 늘어난 기능으로 인해, 코드 대공사가 필요해졌습니다.

## Tasks

- [ ] test_0-intro.py에 스트림릿 사용방법과 더불어, 크롤링 함수도 추가 (데이터 저장 이슈)
- [ ] test_1-all-posting.py에서 원티드, 사람인 따로 볼 수 있도록 selectbox 추가 생성
- [ ] test_2-skills.py에서 3가지 역량을 전처리 후, 프롬프트로 명사 생성
