### ISSUE TITLE
문장 유사도 분석

### ISSUE THREAD

**Issue by HongJaeMin** [DS-Job-Flow/test-repo#19]
## Tasks

- [x] 요약된 문장 간 유사도 분석
- [x] 높은 유사도를 가지는 문장끼리 모아서 프롬프트를 사용해 한 문장으로 요약
- [x] 높은 유사도, 낮은 유사도 총 2가지 버전의 결과를 도출
