### ISSUE TITLE
Sprint 1 수행

### ISSUE THREAD

**Issue by HongJaeMin** [DS-Job-Flow/test-repo#3]
## Description

test_1-all-posting.py, test_2-skills.py, test_4-latest-it-news.py 수정

## Tasks

- [ ] Streamlit 사용 방법은 노션 링크 기재
- [ ] Wanted 함수 안에 있는 Lin, Com, ... 리스트 밖으로 빼기
- [ ] IT WORLD에서 최신 신문 수집하는 함수 추가
- [ ] response 아웃풋은 특정 경로에 저장하기 (해당 경로에 아웃풋 없으면 API 수행하도록)
- [ ] test_4-latest-it-news.py 스트림릿 구성
