### ISSUE TITLE
Sprint 1 수행 (윤기창)

### ISSUE THREAD

**Issue by YunGichang7** [DS-Job-Flow/test-repo#4]
## Description

test_0-intro.py, test_1-all-posting.py, test_3-major-company.py 수정

## Tasks

- [x] 크롬 드라이버 매니저 추가
- [ ] OpenAI API 발급 방법 작성 및 입력칸 생성
- [x] Wanted 함수 안에 있는 Lin, Com, ... 리스트 밖으로 빼기
- [x] 사람인에서 채용공고 수집하는 함수 추가
- [x] 사람인에서 대기업 수집하는 함수 추가
- [ ] test_3-major-company.py 스트림릿 구성
